[build]
  command = "pnpm build"
  publish = "out"

[build.environment]
  NODE_VERSION = "22.13.0"

[dev]
  command = "pnpm dev"
  targetPort = 3000

[[redirects]]
  from = "/work"
  to = "/projects"
  status = 301

[[redirects]]
  from = "/writing"
  to = "/posts"
  status = 301

[[redirects]]
  from = "/photography"
  to = "/photos"
  status = 301
